-- ============================================================================
-- FAL & ASTRO V2 ULTIMATE MIGRATION
-- "Self-Running Mystic Super App" with GDPR/KVKK Compliance
-- IDEMPOTENT: Safe to run multiple times
-- ============================================================================

-- ============================================================================
-- 1. LEGAL & COMPLIANCE (GDPR/KVKK)
-- ============================================================================

-- Add legal acceptance tracking to profiles
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS terms_version VARCHAR(20) DEFAULT '1.0',
ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS privacy_version VARCHAR(20) DEFAULT '1.0',
ADD COLUMN IF NOT EXISTS privacy_accepted_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS marketing_consent BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS marketing_consent_at TIMESTAMPTZ;

-- Legal documents versions table
CREATE TABLE IF NOT EXISTS legal_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    doc_type VARCHAR(50) NOT NULL, -- 'terms', 'privacy', 'kvkk'
    version VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    locale VARCHAR(5) DEFAULT 'tr',
    effective_date DATE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(doc_type, version, locale)
);

-- User consent audit log (immutable)
CREATE TABLE IF NOT EXISTS consent_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    consent_type VARCHAR(50) NOT NULL, -- 'terms', 'privacy', 'marketing', 'data_deletion'
    action VARCHAR(20) NOT NULL, -- 'accepted', 'withdrawn', 'requested'
    version VARCHAR(20),
    ip_address INET,
    user_agent TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_consent_audit_user ON consent_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_consent_audit_type ON consent_audit_log(consent_type, action);

-- ============================================================================
-- 2. GAMIFICATION & ENGAGEMENT
-- ============================================================================

-- Add gamification fields to profiles
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS credits INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS streak_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS longest_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_active_date DATE,
ADD COLUMN IF NOT EXISTS total_readings INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS experience_points INTEGER DEFAULT 0;

-- User achievements
CREATE TABLE IF NOT EXISTS achievements (
    id VARCHAR(50) PRIMARY KEY,
    title_tr VARCHAR(100) NOT NULL,
    title_en VARCHAR(100) NOT NULL,
    description_tr TEXT,
    description_en TEXT,
    icon_name VARCHAR(50),
    points INTEGER DEFAULT 10,
    category VARCHAR(50), -- 'streak', 'reading', 'social', 'special'
    requirement_type VARCHAR(50), -- 'count', 'streak', 'date', 'custom'
    requirement_value INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User earned achievements
CREATE TABLE IF NOT EXISTS user_achievements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    achievement_id VARCHAR(50) NOT NULL REFERENCES achievements(id),
    earned_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, achievement_id)
);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON user_achievements(user_id);

-- ============================================================================
-- 3. AUTOMATED DAILY CONTENT (SELF-FEEDING SYSTEM)
-- ============================================================================

-- Daily affirmations (auto-generated by CRON)
CREATE TABLE IF NOT EXISTS daily_affirmations (
    date DATE NOT NULL,
    zodiac_sign VARCHAR(20) NOT NULL,
    content_text TEXT NOT NULL,
    theme VARCHAR(50), -- 'love', 'career', 'health', 'spiritual'
    mood_keywords TEXT[], -- ['positive', 'energetic', 'calm']
    lucky_number INTEGER,
    lucky_color VARCHAR(30),
    power_crystal VARCHAR(50),
    image_prompt TEXT, -- For AI image generation
    theme_image_url TEXT,
    locale VARCHAR(5) DEFAULT 'tr',
    is_manually_edited BOOLEAN DEFAULT FALSE,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    edited_at TIMESTAMPTZ,
    edited_by UUID REFERENCES auth.users(id),
    PRIMARY KEY (date, zodiac_sign, locale)
);

CREATE INDEX IF NOT EXISTS idx_daily_affirmations_date ON daily_affirmations(date);
CREATE INDEX IF NOT EXISTS idx_daily_affirmations_sign ON daily_affirmations(zodiac_sign);

-- Daily tarot card (auto-generated)
CREATE TABLE IF NOT EXISTS daily_tarot (
    date DATE NOT NULL,
    zodiac_sign VARCHAR(20) NOT NULL,
    card_name VARCHAR(100) NOT NULL,
    card_meaning_tr TEXT NOT NULL,
    card_meaning_en TEXT,
    card_advice_tr TEXT,
    card_advice_en TEXT,
    card_image_url TEXT,
    is_reversed BOOLEAN DEFAULT FALSE,
    locale VARCHAR(5) DEFAULT 'tr',
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (date, zodiac_sign, locale)
);

-- ============================================================================
-- 4. DREAM INTERPRETATION (NEW FEATURE)
-- ============================================================================

CREATE TABLE IF NOT EXISTS dreams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    dream_text TEXT NOT NULL,
    voice_recording_path TEXT, -- Storage path if voice input
    is_voice_input BOOLEAN DEFAULT FALSE,
    transcription_text TEXT, -- Voice-to-text result
    interpretation TEXT,
    symbols JSONB DEFAULT '[]', -- [{symbol: 'water', meaning: '...'}]
    emotions TEXT[], -- ['fear', 'joy', 'confusion']
    themes TEXT[], -- ['flying', 'falling', 'chase']
    lucky_numbers INTEGER[],
    mood_score INTEGER CHECK (mood_score >= 1 AND mood_score <= 10),
    processing_time_ms INTEGER,
    status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'failed'
    error_message TEXT,
    locale VARCHAR(5) DEFAULT 'tr',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    is_favorite BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_dreams_user ON dreams(user_id);
CREATE INDEX IF NOT EXISTS idx_dreams_status ON dreams(status);
CREATE INDEX IF NOT EXISTS idx_dreams_created ON dreams(created_at DESC);

-- Dream symbols dictionary
CREATE TABLE IF NOT EXISTS dream_symbols (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol_name VARCHAR(100) NOT NULL,
    category VARCHAR(50), -- 'animal', 'object', 'place', 'person', 'action'
    meaning_tr TEXT NOT NULL,
    meaning_en TEXT,
    positive_aspect TEXT,
    negative_aspect TEXT,
    related_symbols TEXT[],
    frequency_score INTEGER DEFAULT 0, -- How often this symbol appears
    locale VARCHAR(5) DEFAULT 'tr',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(symbol_name, locale)
);

-- ============================================================================
-- 5. ENHANCED FORTUNE READINGS
-- ============================================================================

-- Update fortune_readings table
ALTER TABLE fortune_readings
ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER,
ADD COLUMN IF NOT EXISTS model_used VARCHAR(50),
ADD COLUMN IF NOT EXISTS confidence_score DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS shared_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0;

-- Fortune sharing (for social features)
CREATE TABLE IF NOT EXISTS fortune_shares (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reading_id UUID NOT NULL REFERENCES fortune_readings(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    platform VARCHAR(30), -- 'instagram', 'whatsapp', 'twitter', 'copy_link'
    shared_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fortune_shares_reading ON fortune_shares(reading_id);

-- ============================================================================
-- 6. SYNASTRY & COMPATIBILITY (NEW)
-- ============================================================================

CREATE TABLE IF NOT EXISTS synastry_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    partner_name VARCHAR(100),
    partner_birth_date DATE NOT NULL,
    partner_birth_time TIME,
    partner_birth_city VARCHAR(100) NOT NULL,
    partner_birth_country VARCHAR(100) NOT NULL,
    partner_birth_lat DECIMAL(10, 7),
    partner_birth_lng DECIMAL(10, 7),
    partner_zodiac_sign VARCHAR(20),
    compatibility_score INTEGER CHECK (compatibility_score >= 0 AND compatibility_score <= 100),
    overall_summary TEXT,
    emotional_compatibility TEXT,
    intellectual_compatibility TEXT,
    physical_compatibility TEXT,
    long_term_potential TEXT,
    challenges TEXT,
    advice TEXT,
    aspect_details JSONB DEFAULT '{}', -- Detailed planetary aspects
    chart_svg TEXT, -- SVG of combined chart
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_synastry_user ON synastry_reports(user_id);

-- ============================================================================
-- 7. MONETIZATION & CREDITS
-- ============================================================================

-- Credit packages
CREATE TABLE IF NOT EXISTS credit_packages (
    id VARCHAR(50) PRIMARY KEY,
    name_tr VARCHAR(100) NOT NULL,
    name_en VARCHAR(100),
    credits INTEGER NOT NULL,
    price_usd DECIMAL(10, 2) NOT NULL,
    price_try DECIMAL(10, 2),
    bonus_credits INTEGER DEFAULT 0,
    is_popular BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    store_product_id_ios VARCHAR(100),
    store_product_id_android VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credit transactions
CREATE TABLE IF NOT EXISTS credit_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL, -- positive = add, negative = spend
    balance_after INTEGER,
    transaction_type VARCHAR(30) NOT NULL, -- 'purchase', 'spend', 'reward', 'refund', 'admin', 'ad_reward'
    description TEXT,
    reference_id UUID, -- ID of the reading/report that used credits
    reference_type VARCHAR(50), -- 'fortune', 'dream', 'synastry', 'astro_report'
    package_id VARCHAR(50) REFERENCES credit_packages(id),
    store_transaction_id VARCHAR(255), -- App Store/Play Store transaction ID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_credit_transactions_user ON credit_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_type ON credit_transactions(transaction_type);

-- Ad rewards tracking
CREATE TABLE IF NOT EXISTS ad_rewards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    ad_network VARCHAR(30) NOT NULL, -- 'admob', 'unity', 'applovin'
    ad_unit_id VARCHAR(100),
    reward_type VARCHAR(30) DEFAULT 'credit', -- 'credit', 'free_reading'
    reward_amount INTEGER DEFAULT 1,
    watched_at TIMESTAMPTZ DEFAULT NOW(),
    ip_address INET,
    device_id VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_ad_rewards_user ON ad_rewards(user_id);
CREATE INDEX IF NOT EXISTS idx_ad_rewards_date ON ad_rewards(watched_at);

-- ============================================================================
-- 8. APP CONFIGURATION
-- ============================================================================

CREATE TABLE IF NOT EXISTS app_config (
    key VARCHAR(100) PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_by UUID REFERENCES auth.users(id)
);

-- Insert default config
INSERT INTO app_config (key, value, description) VALUES
('min_version_ios', '"1.0.0"', 'Minimum required iOS app version'),
('min_version_android', '"1.0.0"', 'Minimum required Android app version'),
('maintenance_mode', 'false', 'Enable maintenance mode'),
('maintenance_message', '{"tr": "Bakım çalışması devam ediyor.", "en": "Maintenance in progress."}', 'Maintenance message'),
('feature_flags', '{"dreams_enabled": true, "synastry_enabled": true, "ads_enabled": true, "social_sharing": true}', 'Feature toggles'),
('credit_costs', '{"fortune": 1, "dream": 1, "synastry": 3, "astro_report": 2}', 'Credit cost per feature'),
('ad_reward_credits', '1', 'Credits given per rewarded ad'),
('ads_for_free_reading', '3', 'Number of ads to watch for 1 free reading'),
('artificial_delay_seconds', '45', 'Artificial delay for results (UX)'),
('current_terms_version', '"1.0"', 'Current terms of service version'),
('current_privacy_version', '"1.0"', 'Current privacy policy version'),
('daily_free_readings', '1', 'Free readings per day for free users')
ON CONFLICT (key) DO NOTHING;

-- ============================================================================
-- 9. PUSH NOTIFICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS push_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    platform VARCHAR(20) NOT NULL, -- 'ios', 'android', 'web'
    device_info JSONB DEFAULT '{}',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, token)
);

CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_push_tokens_active ON push_tokens(is_active) WHERE is_active = TRUE;

-- Notification templates
CREATE TABLE IF NOT EXISTS notification_templates (
    id VARCHAR(50) PRIMARY KEY,
    title_tr VARCHAR(255) NOT NULL,
    title_en VARCHAR(255),
    body_tr TEXT NOT NULL,
    body_en TEXT,
    category VARCHAR(50), -- 'daily', 'streak', 'promotional', 'transactional'
    data_schema JSONB, -- Expected data payload structure
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notification history
CREATE TABLE IF NOT EXISTS notification_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    template_id VARCHAR(50) REFERENCES notification_templates(id),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    platform VARCHAR(20),
    status VARCHAR(20) DEFAULT 'sent', -- 'sent', 'delivered', 'failed', 'clicked'
    error_message TEXT,
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    delivered_at TIMESTAMPTZ,
    clicked_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notification_history_user ON notification_history(user_id);
CREATE INDEX IF NOT EXISTS idx_notification_history_sent ON notification_history(sent_at DESC);

-- ============================================================================
-- 10. ADMIN & ANALYTICS
-- ============================================================================

-- Admin roles
CREATE TABLE IF NOT EXISTS admin_roles (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role VARCHAR(30) NOT NULL DEFAULT 'moderator', -- 'super_admin', 'admin', 'moderator', 'content_editor'
    permissions JSONB DEFAULT '[]',
    granted_by UUID REFERENCES auth.users(id),
    granted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Analytics events (for custom tracking)
CREATE TABLE IF NOT EXISTS analytics_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    event_name VARCHAR(100) NOT NULL,
    event_params JSONB DEFAULT '{}',
    session_id VARCHAR(100),
    platform VARCHAR(20),
    app_version VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analytics_events_name ON analytics_events(event_name);
CREATE INDEX IF NOT EXISTS idx_analytics_events_user ON analytics_events(user_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_date ON analytics_events(created_at DESC);

-- Daily aggregated stats
CREATE TABLE IF NOT EXISTS daily_stats (
    date DATE PRIMARY KEY,
    total_users INTEGER DEFAULT 0,
    new_users INTEGER DEFAULT 0,
    active_users INTEGER DEFAULT 0,
    total_fortunes INTEGER DEFAULT 0,
    total_dreams INTEGER DEFAULT 0,
    total_synastry INTEGER DEFAULT 0,
    total_revenue_usd DECIMAL(10, 2) DEFAULT 0,
    total_ad_views INTEGER DEFAULT 0,
    avg_session_duration_seconds INTEGER DEFAULT 0,
    calculated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 11. ROW LEVEL SECURITY POLICIES
-- ============================================================================

-- Dreams RLS
ALTER TABLE dreams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dreams_select_own ON dreams;
CREATE POLICY dreams_select_own ON dreams FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS dreams_insert_own ON dreams;
CREATE POLICY dreams_insert_own ON dreams FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS dreams_update_own ON dreams;
CREATE POLICY dreams_update_own ON dreams FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS dreams_delete_own ON dreams;
CREATE POLICY dreams_delete_own ON dreams FOR DELETE
    USING (auth.uid() = user_id);

-- Synastry RLS
ALTER TABLE synastry_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS synastry_select_own ON synastry_reports;
CREATE POLICY synastry_select_own ON synastry_reports FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS synastry_insert_own ON synastry_reports;
CREATE POLICY synastry_insert_own ON synastry_reports FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Credit transactions RLS
ALTER TABLE credit_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS credit_transactions_select_own ON credit_transactions;
CREATE POLICY credit_transactions_select_own ON credit_transactions FOR SELECT
    USING (auth.uid() = user_id);

-- Daily affirmations (public read)
ALTER TABLE daily_affirmations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS daily_affirmations_select_all ON daily_affirmations;
CREATE POLICY daily_affirmations_select_all ON daily_affirmations FOR SELECT
    USING (TRUE);

-- Consent audit log (user can only see their own)
ALTER TABLE consent_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS consent_audit_select_own ON consent_audit_log;
CREATE POLICY consent_audit_select_own ON consent_audit_log FOR SELECT
    USING (auth.uid() = user_id);

-- Push tokens RLS
ALTER TABLE push_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS push_tokens_select_own ON push_tokens;
CREATE POLICY push_tokens_select_own ON push_tokens FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS push_tokens_insert_own ON push_tokens;
CREATE POLICY push_tokens_insert_own ON push_tokens FOR INSERT
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS push_tokens_update_own ON push_tokens;
CREATE POLICY push_tokens_update_own ON push_tokens FOR UPDATE
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS push_tokens_delete_own ON push_tokens;
CREATE POLICY push_tokens_delete_own ON push_tokens FOR DELETE
    USING (auth.uid() = user_id);

-- User achievements RLS
ALTER TABLE user_achievements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_achievements_select_own ON user_achievements;
CREATE POLICY user_achievements_select_own ON user_achievements FOR SELECT
    USING (auth.uid() = user_id);

-- ============================================================================
-- 12. FUNCTIONS & TRIGGERS
-- ============================================================================

-- Function to update streak
CREATE OR REPLACE FUNCTION update_user_streak()
RETURNS TRIGGER AS $$
BEGIN
    -- Check if user was active yesterday
    IF NEW.last_active_date = CURRENT_DATE - INTERVAL '1 day' THEN
        -- Continue streak
        NEW.streak_count := OLD.streak_count + 1;
        IF NEW.streak_count > OLD.longest_streak THEN
            NEW.longest_streak := NEW.streak_count;
        END IF;
    ELSIF NEW.last_active_date < CURRENT_DATE - INTERVAL '1 day' THEN
        -- Break streak
        NEW.streak_count := 1;
    END IF;

    NEW.last_active_date := CURRENT_DATE;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Function to deduct credits
CREATE OR REPLACE FUNCTION deduct_credits(
    p_user_id UUID,
    p_amount INTEGER,
    p_reference_type VARCHAR(50),
    p_reference_id UUID DEFAULT NULL
)
RETURNS BOOLEAN AS $$
DECLARE
    v_current_credits INTEGER;
    v_new_balance INTEGER;
BEGIN
    -- Get current credits
    SELECT credits INTO v_current_credits
    FROM profiles
    WHERE id = p_user_id
    FOR UPDATE;

    IF v_current_credits < p_amount THEN
        RETURN FALSE;
    END IF;

    v_new_balance := v_current_credits - p_amount;

    -- Update profile
    UPDATE profiles
    SET credits = v_new_balance
    WHERE id = p_user_id;

    -- Log transaction
    INSERT INTO credit_transactions (user_id, amount, balance_after, transaction_type, reference_type, reference_id)
    VALUES (p_user_id, -p_amount, v_new_balance, 'spend', p_reference_type, p_reference_id);

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Function to add credits
CREATE OR REPLACE FUNCTION add_credits(
    p_user_id UUID,
    p_amount INTEGER,
    p_transaction_type VARCHAR(30),
    p_description TEXT DEFAULT NULL
)
RETURNS INTEGER AS $$
DECLARE
    v_new_balance INTEGER;
BEGIN
    UPDATE profiles
    SET credits = credits + p_amount
    WHERE id = p_user_id
    RETURNING credits INTO v_new_balance;

    -- Log transaction
    INSERT INTO credit_transactions (user_id, amount, balance_after, transaction_type, description)
    VALUES (p_user_id, p_amount, v_new_balance, p_transaction_type, p_description);

    RETURN v_new_balance;
END;
$$ LANGUAGE plpgsql;

-- Function to log consent
CREATE OR REPLACE FUNCTION log_consent(
    p_user_id UUID,
    p_consent_type VARCHAR(50),
    p_action VARCHAR(20),
    p_version VARCHAR(20) DEFAULT NULL,
    p_ip_address INET DEFAULT NULL,
    p_user_agent TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_log_id UUID;
BEGIN
    INSERT INTO consent_audit_log (user_id, consent_type, action, version, ip_address, user_agent)
    VALUES (p_user_id, p_consent_type, p_action, p_version, p_ip_address, p_user_agent)
    RETURNING id INTO v_log_id;

    -- Update profile
    IF p_consent_type = 'terms' AND p_action = 'accepted' THEN
        UPDATE profiles
        SET terms_version = p_version, terms_accepted_at = NOW()
        WHERE id = p_user_id;
    ELSIF p_consent_type = 'privacy' AND p_action = 'accepted' THEN
        UPDATE profiles
        SET privacy_version = p_version, privacy_accepted_at = NOW()
        WHERE id = p_user_id;
    ELSIF p_consent_type = 'marketing' THEN
        UPDATE profiles
        SET marketing_consent = (p_action = 'accepted'),
            marketing_consent_at = NOW()
        WHERE id = p_user_id;
    END IF;

    RETURN v_log_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 13. INSERT DEFAULT DATA
-- ============================================================================

-- Default achievements
INSERT INTO achievements (id, title_tr, title_en, description_tr, description_en, icon_name, points, category, requirement_type, requirement_value) VALUES
('first_fortune', 'İlk Fal', 'First Fortune', 'İlk kahve falınızı baktırdınız', 'Got your first coffee fortune', 'coffee', 10, 'reading', 'count', 1),
('fortune_master', 'Fal Ustası', 'Fortune Master', '50 kahve falı baktırdınız', 'Got 50 coffee fortunes', 'star', 100, 'reading', 'count', 50),
('dream_explorer', 'Rüya Kaşifi', 'Dream Explorer', 'İlk rüya yorumunuzu aldınız', 'Got your first dream interpretation', 'moon', 10, 'reading', 'count', 1),
('week_streak', 'Haftalık Sadakat', 'Weekly Streak', '7 gün üst üste giriş yaptınız', 'Logged in 7 days in a row', 'fire', 50, 'streak', 'streak', 7),
('month_streak', 'Aylık Sadakat', 'Monthly Streak', '30 gün üst üste giriş yaptınız', 'Logged in 30 days in a row', 'trophy', 200, 'streak', 'streak', 30),
('social_butterfly', 'Sosyal Kelebek', 'Social Butterfly', '10 fal paylaştınız', 'Shared 10 fortunes', 'share', 30, 'social', 'count', 10),
('stargazer', 'Yıldız Avcısı', 'Stargazer', 'Tüm burç raporlarını okudunuz', 'Read all zodiac reports', 'stars', 75, 'special', 'custom', 12)
ON CONFLICT (id) DO NOTHING;

-- Default credit packages
INSERT INTO credit_packages (id, name_tr, name_en, credits, price_usd, price_try, bonus_credits, is_popular) VALUES
('starter', 'Başlangıç', 'Starter', 5, 0.99, 29.99, 0, FALSE),
('popular', 'Popüler', 'Popular', 15, 2.99, 79.99, 2, TRUE),
('premium', 'Premium', 'Premium', 50, 7.99, 199.99, 10, FALSE),
('ultimate', 'Sınırsız', 'Ultimate', 150, 19.99, 499.99, 50, FALSE)
ON CONFLICT (id) DO NOTHING;

-- Default notification templates
INSERT INTO notification_templates (id, title_tr, title_en, body_tr, body_en, category) VALUES
('daily_horoscope', 'Günlük Burcunuz Hazır!', 'Your Daily Horoscope is Ready!', '{{zodiac_label}} burcu için bugünün mesajı sizi bekliyor ✨', 'Today''s message for {{zodiac_label}} is waiting for you ✨', 'daily'),
('streak_reminder', 'Serinizi Kaybetmeyin!', 'Don''t Lose Your Streak!', '{{streak_count}} günlük seriniz tehlikede! Bugün giriş yapın 🔥', 'Your {{streak_count}}-day streak is at risk! Login today 🔥', 'streak'),
('fortune_ready', 'Falınız Hazır!', 'Your Fortune is Ready!', 'Kahve falınız yorumlandı. Hemen görüntüleyin ☕', 'Your coffee fortune is ready. View it now ☕', 'transactional'),
('dream_ready', 'Rüya Yorumunuz Hazır!', 'Your Dream Interpretation is Ready!', 'Rüyanızın anlamı çözümlendi 🌙', 'Your dream has been interpreted 🌙', 'transactional')
ON CONFLICT (id) DO NOTHING;

-- Default legal documents
INSERT INTO legal_documents (doc_type, version, title, content, locale, effective_date) VALUES
('terms', '1.0', 'Kullanım Koşulları', 'Fal & Astro uygulamasını kullanarak aşağıdaki koşulları kabul etmiş olursunuz...

1. GENEL KOŞULLAR
Bu uygulama eğlence amaçlıdır ve profesyonel tavsiye yerine geçmez.

2. HİZMET KULLANIMI
Kullanıcılar, uygulamayı yasalara uygun şekilde kullanmayı kabul eder.

3. FİKRİ MÜLKİYET
Tüm içerik ve tasarımlar Fal & Astro''ya aittir.

4. SORUMLULUK REDDİ
Uygulama içerikleri genel bilgi amaçlıdır.

5. DEĞİŞİKLİKLER
Bu koşullar önceden haber verilmeksizin değiştirilebilir.', 'tr', CURRENT_DATE),
('privacy', '1.0', 'Gizlilik Politikası', 'Fal & Astro olarak gizliliğinize önem veriyoruz...

1. TOPLANAN VERİLER
- Hesap bilgileri (e-posta, doğum tarihi)
- Kullanım verileri
- Cihaz bilgileri

2. VERİ KULLANIMI
Verileriniz hizmet sunmak ve iyileştirmek için kullanılır.

3. VERİ PAYLAŞIMI
Verileriniz üçüncü taraflarla satılmaz.

4. VERİ GÜVENLİĞİ
Verileriniz şifrelenerek korunur.

5. HAKLARINIZ (KVKK/GDPR)
- Verilerinize erişim hakkı
- Düzeltme hakkı
- Silme hakkı
- İtiraz hakkı

İletişim: privacy@falastro.com', 'tr', CURRENT_DATE)
ON CONFLICT (doc_type, version, locale) DO NOTHING;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
